# HEY! noname.rb IS AUTOGENERATED FILE, PLEASE DO NOT EDIT IT
# TO UPDATE THE CONTENT PLEASE CHECK .github/workflows/formula-template.rb

class Noname < Formula
  desc "CLI tool to remove personally identifiable information from screenshots ✨"
  homepage "https://github.com/antonKalinin/noname"
  url "https://github.com/antonKalinin/noname/releases/latest/download/noname-macos.tar.gz"
  sha256 "472c47c64263040cf3fbd92acd0f328a880a681b9c11f05e2387009fbd2a0898"
  version "0.1.23"

  def install
    bin.install "noname"
  end
end