name: Update Formula

on:
  repository_dispatch:
    types: [new_release]

jobs:
  test:
    name: Test
    steps:
      - env:
          VERSION: ${{ github.event.client_payload.VERSION }}
        run: echo $VERSION
      - env:
          SHA256: ${{ github.event.client_payload.SHA256 }}
        run: echo $SHA256